apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: mern-tier
data:
  PORT: "3000"
  FRONTEND_URL: "https://frontend.yourdomain.com"
  CLOUDINARY_CLOUD_NAME: "dnodnzm2p"
  CLOUDINARY_API_KEY: "295124719844263"
