apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: three-tier
data:
  VITE_API_BASE_URL: "http://localhost:7000"
  VITE_STRIPE_PUB_KEY: "pk_test_51OYpfoCMgMbcwgSU6FDoVuHjz2Oh9jk2HH0zQCGyv3mH4i4SDkpHYGoVENBfjUwBKR7GgEhzOCYRWyIPIzzLMUBg00jNrzCJ5N"
